import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Mono } from "next/font/google"
import Providers from './providers'

export const metadata: Metadata = {
  title: 'Home Work Chat',
  description: 'Generated by create next app',
}

const font = Roboto_Mono({subsets: ['latin']})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
