import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Mono } from "next/font/google"
import Providers from './providers'
import SideBar2 from '../components/SideBar2'

export const metadata: Metadata = {
  title: 'Home Work Chat',
  description: 'Generated by create next app',
}

const font = Roboto_Mono({subsets: ['latin']})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
        <div className="flex w-full h-screen max-h-full overflow-hidden">
          <SideBar2 />
          <div className="p-1 bg-[var(--black-sb)] w-full">
            <div className="w-full h-full">
              <div className="">
                {children}
              </div>
            </div>
          </div>
        </div>
        </Providers>
      </body>
    </html>
  )
}
